### PR TITLE
Ira merge rigidbot marlin102

### PR DESCRIPTION
**Pull request by seefood**
merged with upstream tag 1.0.2. works on my RigidBot, Not tested LCD because I haven't got one.

### CODE REVIEW

**Comment by seefood** [comment]
Oh yeah, and gimme write access, I promise to stay on my own branches :)

**Comment by guysoft** [comment]
I'll merge it once you tested, then we write this in the wiki :)
Will try testing here later, but printing now.

**Comment by seefood** [comment]
leaving office, going home, I hope to test it in about 2 hours.

**Comment by seefood** [comment]
In file included from Marlin.h:16:0,
                 from temperature.h:24,
                 from rigidpanel.cpp:1:
rigidpanel.cpp: In function 'void lcd_main_menu()':
rigidpanel.cpp:297:24: error: 'MSG_UTILITIES' was not declared in this scope
     MENU_ITEM(submenu, MSG_UTILITIES, lcd_utilities_menu);
                        ^
rigidpanel.cpp:297:5: note: in expansion of macro 'MENU_ITEM'
     MENU_ITEM(submenu, MSG_UTILITIES, lcd_utilities_menu);
     ^
rigidpanel.cpp: In function 'void lcd_prepare_menu()':
rigidpanel.cpp:492:21: error: 'MSG_HEAT_COOL' was not declared in this scope
  MENU_ITEM(submenu, MSG_HEAT_COOL, lcd_heat_cool_menu);
                     ^
rigidpanel.cpp:492:2: note: in expansion of macro 'MENU_ITEM'
  MENU_ITEM(submenu, MSG_HEAT_COOL, lcd_heat_cool_menu);
  ^
Error compiling.

back to the drawing board :(

**Comment by guysoft** [comment]
Got the same here, 
@gregrebholz Have you seen this?

**Comment by gregrebholz** [comment]
No, but I haven't been engaged on the RigidBot modifications to bleeding edge Marlin recently either.  Those errors suggest language.h constants differ from what IAP had from the Marlin they took in 2012 to what we have today, and that's not at all surprising.  Unfortunately rigidpanel.cpp is a modified copy of ultralcd.cpp, to avoid an abundance of if/then blocks for an LCD that few in the world use.  You'll probably need to review the commit history on ultralcd.cpp to see what changes were made for these macros and then backport those to rigidpanel.cpp.

**Comment by seefood** [comment]
Language fixed, now the actual code pains begin :-)

Marlin_main.cpp.o: In function `process_commands()':
Marlin_main.cpp:1930: undefined reference to`lcd_ignore_click(bool)'
Marlin_main.cpp:1940: undefined reference to `lcd_detected()'
Marlin_main.cpp:1950: undefined reference to`lcd_ignore_click(bool)'
collect2: error: ld returned 1 exit status
Error compiling.

**Comment by guysoft** [comment]
Can we somehow ignore the LCD for now?
@gregrebholz I saw you somehow set the standard marlin LCD in RBCE, would that stop the LCD errors?

**Comment by gregrebholz** [comment]
Yeah, my most recent attempt at RB support for Marlin is here: https://github.com/gregrebholz/Marlin/tree/rigidboard  and includes only the pin assignments for the basic RigidBoard.  I don't have support for either the RigidPanel LCD nor other "Marlin" LCDs there... but you could easily add those other Marlin LCDs to it.  It just needs pins_rigidboard.h values for the LCD pin outs.

In your code you'd just want to remove the #define RIGID_PANEL in the Configuration.h.  I believe that would prevent rigidpanel.cpp from even passing through the compiler.

**Comment by seefood** [comment]
Well, my branch compiled and uploaded, let's print!

**Comment by guysoft** [comment]
@seefood Did you push it? I don't see new commits.
Also, as said before, will merge after it actually prints.

**Comment by seefood** [comment]
Actually printing now.

**Comment by seefood** [comment]
Well, it's been 4 days, lots of good prints with Cura and now OctoPrint... Ready to merge if you ask me. I have not seen any visible improvements, but it works...

**Comment by guysoft** [comment]
Seems to be working here too. If there is a regression lets treat it in its own thread.

**Pull request merged**
